# workflow.yaml
# Workflow definition for ChainLease lease notification workflow

name: lease-notification-workflow
version: 1.0.0
description: Sends email notifications to tenants when leases are activated
